general {
    hide_cursor = true
}

background {
    monitor =
    path = /usr/share/backgrounds/ben-bazzite/aurora-glass.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.55
    vibrancy = 0.20
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(230, 237, 247, 1.0)
    font_size = 72
    font_family = Roboto Medium
    position = 0, 155
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %B %-d')"
    color = rgba(174, 185, 214, 1.0)
    font_size = 15
    font_family = Roboto
    position = 0, 92
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 58
    outline_thickness = 2
    dots_size = 0.24
    dots_spacing = 0.28
    outer_color = rgba(110, 231, 250, 0.90)
    inner_color = rgba(11, 16, 32, 0.88)
    font_color = rgba(230, 237, 247, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="##aeb9d6">Password</span>
    hide_input = false
    check_color = rgba(155, 123, 255, 1.0)
    fail_color = rgba(255, 122, 144, 1.0)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    rounding = 16
    position = 0, -20
    halign = center
    valign = center
}
