#!/bin/bash
exec env GTK_THEME=Adwaita:dark zenity --text-info \
    --title="Ben Bazzite shortcuts" \
    --width=620 \
    --height=650 \
    --filename=/usr/share/doc/ben-bazzite/hyprland-keybinds.txt
