#!/bin/bash
exec env GTK_THEME=BenBazziteShortcuts zenity --text-info \
    --title="Ben Bazzite shortcuts" \
    --width=680 \
    --height=720 \
    --font="Roboto 11" \
    --filename=/usr/share/doc/ben-bazzite/hyprland-keybinds.txt
